### ISSUE TITLE
include property (switch on/off files)

### ISSUE THREAD

**Issue by nwieters** [esm-tools/esm_runscripts#209]
From the `files` dictionary, take only the files that are listed in `simulation_files`, a dictionary equivalent to the old `<type>_files`

**the old way**
```yaml
greenhouse_ssp:
    name: greenhouse
    path_in_pool: ...


choose_scenario:
     ssp:
         simulation_files: # Whatever file is not here, it's not used
               greenhouse: greenhouse_ssp
```

**choose_ and add_ idea**

```yaml
greenhouse_ssp:
    name: greenhouse
    path_in_pool: ...


choose_scenario:
     ssp:
         add_files:
               ${greenhouse_ssp}
```

**Include files idea**

```yaml
files:
    greenhouse_ssp:
        name: greenhouse
        path_in_pool: ...
        include: false

choose_scenario:
    ssp:
         include_files:
               greenhouse_ssp: true
```

**Include files without include_files**
```yaml
files:
    greenhouse_ssp:
        name: greenhouse
        path_in_pool: ...
        include: false

choose_scenario:
    ssp:
         add_files:
               greenhouse_ssp:
                   include: true
```
